"""appupdate 模块清单：声明 CLI 命令组 / Web 路由 / 前端页签接入点。

CLI 命令组在 aups/core/cli.py 中按此清单注册；Web 路由在 aups/web/app.py 中按此挂载。
"""

MANIFEST = {
    "name": "appupdate",
    "title": "应用更新管理",
    "version": "1.0.0",
    "description": "APK 更新：应用注册/版本、存储与配额、下载统计、CI 上传用户与 SSH 公钥",
    "type": "external",
    "attr": "功能",
    "depends": [{"capability": "proxy"}],
    "cli_groups": ["app", "storage", "user", "ssh"],
    "api_module": "aups.modules.appupdate.api",
    "api_paths": [
        "/api/apps",
        "/api/apps/{name}",
        "/api/apps/{name}/versions",
        "/api/apps/{name}/versions/{version}/lock",
        "/api/apps/{name}/versions/{version}/unlock",
        "/api/apps/{name}/quota",
        "/api/apps/caddy",
        "/api/apps/discover",
        "/api/storage",
        "/api/storage/usage",
        "/api/storage/apks",
        "/api/storage/quota",
        "/api/storage/enforce",
        "/api/storage/delete",
        "/api/stats/downloads",
        "/api/users",
        "/api/users/{name}",
        "/api/users/{name}/dirs",
        "/api/users/{name}/dirs/remove",
        "/api/ssh",
        "/api/ssh/{user}",
        "/api/ssh/{user}/{index}",
    ],
    "frontend_tabs": ["apps", "storage", "users", "ssh"],
    "modules": ["apps", "storage", "downloads", "users", "sshkeys"],
    "entry": [
        {"id": "apps", "title": "应用管理"},
        {"id": "users", "title": "CI 用户"},
        {"id": "ssh", "title": "SSH 公钥"},
    ],
    "plugins": [
        {"id": "apps", "title": "应用管理",
         "description": "应用注册/版本、存储与配额、APK 管理、未注册检测"},
        {"id": "users", "title": "CI 用户",
         "description": "APK 上传账号与目录 ACL 授权"},
        {"id": "ssh", "title": "SSH 公钥",
         "description": "CI 用户的上传鉴权公钥管理"},
    ],
    "cards": [
        {"id": "downloads", "title": "下载统计",
         "min_w": 1, "max_w": 3, "default_w": 2, "min_h": 1, "max_h": 2, "default_h": 1},
        {"id": "appsoverview", "title": "应用概览",
         "min_w": 1, "max_w": 3, "default_w": 1, "min_h": 1, "max_h": 2, "default_h": 1},
    ],
}
