window.AUPS_PLUGINS=window.AUPS_PLUGINS||{};
window.AUPS_PLUGINS.certmanager=(function(){
 function certDate(value){return value == null ? '未知' : new Date(value*1000).toLocaleString();}
 function certRemaining(c){return c.remaining_days == null ? '无法读取' : c.remaining_days < 0 ? '已过期' : c.remaining_days === 0 ? '不足 1 天' : c.remaining_days+' 天';}
 async function main(){const d=await api('GET','/api/certmanager/certificates');const rows=(d.certificates||[]).map((c,i)=>'<tr><td>'+esc(c.domain)+'</td><td>'+esc(c.provider || c.source || '本机证书')+'</td><td>'+esc(certDate(c.issued_at))+'</td><td>'+esc(certDate(c.expires_at))+'</td><td>'+esc(certRemaining(c))+'</td><td class="ellipsis">'+esc(c.cert)+'</td><td>'+(c.managed === false ? '<span class="mut">由原服务管理</span>' : '<button class="ghost" onclick="AUPS_PLUGINS.certmanager.renew(\''+esc(c.provider)+'\')">续期</button> <button class="ghost" onclick="AUPS_PLUGINS.certmanager.update(\''+esc(c.provider)+'\',\''+esc(c.domain)+'\')">更新</button> <button class="danger" onclick="AUPS_PLUGINS.certmanager.del(\''+esc(c.provider)+'\',\''+esc(c.domain)+'\')">删除</button>')+'</td></tr>').join('');view.innerHTML='<div class="card"><h2>SSL 证书管理</h2><p class="mut">时间按当前浏览器时区显示；签发时间取证书生效时间，并非提交申请的时间。</p><div class="row"><input id="cmDomain" placeholder="example.com"><select id="cmProvider">'+(d.providers||[]).map(x=>'<option>'+esc(x)+'</option>').join('')+'</select><button onclick="AUPS_PLUGINS.certmanager.issue()">申请证书</button><button class="ghost" onclick="AUPS_PLUGINS.certmanager.renew()">全部续期</button></div><table style="margin-top:12px"><tr><th>域名</th><th>签发器</th><th>签发 / 生效时间</th><th>到期时间</th><th>剩余有效期</th><th>证书</th><th>操作</th></tr>'+rows+'</table></div>'}
 async function issue(){await api('POST','/api/certmanager/issue',{domain:document.getElementById('cmDomain').value.trim(),provider:document.getElementById('cmProvider').value});await main()}
 async function renew(provider,domain){await api('POST','/api/certmanager/renew',{provider,domain});await main()}
 async function update(provider,domain){await api('POST','/api/certmanager/update',{provider,domain});await main()}
 async function del(provider,domain){if(confirm('删除 '+domain+' 的证书？')){await api('POST','/api/certmanager/delete',{provider,domain});await main()}}
 return {title:'SSL 证书管理',sections:[{id:'main',title:'证书管理'}],go:main,open:main,issue,renew,update,del};
})();
