window.AUPS_PLUGINS=window.AUPS_PLUGINS||{};
window.AUPS_PLUGINS.certmanager=(function(){
 async function main(){const d=await api('GET','/api/certmanager/certificates');const rows=(d.certificates||[]).map((c,i)=>'<tr><td>'+esc(c.domain)+'</td><td>'+esc(c.provider)+'</td><td class="ellipsis">'+esc(c.cert)+'</td><td><button class="ghost" onclick="AUPS_PLUGINS.certmanager.renew(\''+esc(c.provider)+'\')">续期</button> <button class="ghost" onclick="AUPS_PLUGINS.certmanager.update(\''+esc(c.provider)+'\',\''+esc(c.domain)+'\')">更新</button> <button class="danger" onclick="AUPS_PLUGINS.certmanager.del(\''+esc(c.provider)+'\',\''+esc(c.domain)+'\')">删除</button></td></tr>').join('');view.innerHTML='<div class="card"><h2>SSL 证书管理</h2><div class="row"><input id="cmDomain" placeholder="example.com"><select id="cmProvider">'+(d.providers||[]).map(x=>'<option>'+esc(x)+'</option>').join('')+'</select><button onclick="AUPS_PLUGINS.certmanager.issue()">申请证书</button><button class="ghost" onclick="AUPS_PLUGINS.certmanager.renew()">全部续期</button></div><table style="margin-top:12px"><tr><th>域名</th><th>签发器</th><th>证书</th><th>操作</th></tr>'+rows+'</table></div>'}
 async function issue(){await api('POST','/api/certmanager/issue',{domain:document.getElementById('cmDomain').value.trim(),provider:document.getElementById('cmProvider').value});await main()}
 async function renew(provider){await api('POST','/api/certmanager/renew',{provider});await main()}
 async function update(provider,domain){await api('POST','/api/certmanager/update',{provider,domain});await main()}
 async function del(provider,domain){if(confirm('删除 '+domain+' 的证书？')){await api('POST','/api/certmanager/delete',{provider,domain});await main()}}
 return {title:'SSL 证书管理',sections:[{id:'main',title:'证书管理'}],go:main,open:main,issue,renew,update,del};
})();
